---
title: "Untargeteda Multi-Omic Integration Scripts"
author: "John Bouranis"
date: "2022-10-28"
output: html_document
---

Output here may have slight differences from the publication due to the
non-stochastic nature of several of the commands, including the rarefaction,
the permutation tests, and others.

```{r setup, include=FALSE}
library(phyloseq)
library(mixOmics)
library(ggfortify)
library(cowplot)
library(tidyverse)
library(magrittr)
library(cowplot)
library(vegan)
library(lme4)
library(phia)
library(lmerTest)
library(pROC)
library(here)
here::i_am('./AllCode.Rmd')

#Help functions:
log_helper <- function(x, min.val){
  log2((x + sqrt(x^2 + min.val^2))/2)
}
#Pareto Scaling:
PS_helper <- function(x){
  (x - mean(x))/sqrt(sd(x, na.rm = T))
}	

#Transformation Functions:
#Log Scaling:
log_transform <- function(mtb){
  mtb_nz <- mtb[ ,which(apply(mtb, 2, sum) != 0)]
  min.val <- min(abs(mtb_nz[mtb_nz!=0]))/10
  mtb_log_trans <- apply(mtb_nz, 2, log_helper, min.val)
  return(mtb_log_trans)
}

#Pareto Scaling:
pareto_scale <- function(mtb){
  mtb_scaled <- apply(mtb, 2, PS_helper) 
  return(mtb_scaled)
}

geoMean <- function(x) exp(mean(log(x)))
centerHelper <- function(x) log(x/geoMean(x))
clr <- function(x){
  nz <- data.frame(apply(x, 2, function(y) replace(y, which(y == 0), 1)))
  data.frame(apply(nz, 2, centerHelper))
}

```


```{r Microbiome Data Load In}
asvtab <- readRDS(here('Data/Microbiome/asv_tab.RDS'))
taxatab <- readRDS(here('Data/Microbiome/tax_tab.RDS'))
metadata <- read.csv(here('Data/Microbiome/microbiome_metadata.csv'))

metadata %<>% mutate(group = ifelse(group == 'A', 'C_Type', 'E_type'))

#Factorize and set the levels on the metadata
metadata$treatment %<>% factor(levels = c('fecal_stock', 'no_veg', 'broc', 'brus', 'combo', 'control_digest'))
metadata$fecal_sample %<>% factor(levels = c('T5631','T5632','T6260','T6291','T4669','T1995','T5627','T5717','T5854','T6382')) 

rownames(metadata) <- metadata$sample
rownames(asvtab) <-metadata$sample
ps_raw <- phyloseq(otu_table(asvtab, taxa_are_rows = FALSE),
               sample_data(metadata),
               tax_table(taxatab))

#Give arbitrary names to the taxa as opposed to keeping as just DNA-sequences which identify them
taxa_names(ps_raw) <- paste0("ASV", seq(ntaxa(ps_raw)))

#Fill in missing genus names:
renames <- rownames(tax_table(ps_raw)[is.na(tax_table(ps_raw)[, 'Genus'])])
taxdf <- tax_table(ps_raw)[renames,]
renamed_genus <- unname(sapply(taxa_names(taxdf), function(x) paste0('f_', taxdf[x, 'Family'], '_', x)))
tax_table(ps_raw)[renames, 'Genus'] <- renamed_genus

#Remove the control digests, these are not relevant to our analysis
ps_raw <- ps_raw %>% subset_samples(treatment != 'control_digest')
#Agglomerate to the genus level
ps_genera <- ps_raw %>% tax_glom(taxrank = "Genus")
#Remove taxa not seen more than 3 times in at least 20% of the samples
ps_counts <- ps_genera %>% filter_taxa(function(x) sum(x > 3) > (0.2*length(x)), TRUE)
#Convert from counts to relative abundance
ps_relab <- ps_counts %>% transform_sample_counts(function(x) x / sum(x) )
#Filter out low abundance (>1e-5) taxa
ps <- ps_relab %>% filter_taxa(function(x) mean(x) > 1e-5, TRUE)

ps_final <- ps %>% subset_samples(treatment != 'fecal_stock')
#Create the count data
ps_final_c <- ps_counts %>% 
  filter_taxa(function(x) mean(x / sum(x)) > 1e-5, TRUE) %>%
  subset_samples(treatment != 'fecal_stock')

microdata <- cbind(sample = data.frame(sample_data(ps_final))$metabolomics_neg_sample, data.frame(otu_table(ps_final))) %>%
  mutate(sample = gsub('neg', 'ms', sample))

microdata_c <- cbind(sample = data.frame(sample_data(ps_final_c))$metabolomics_neg_sample, data.frame(otu_table(ps_final_c))) %>%
  mutate(sample = gsub('neg', 'ms', sample))

```


```{r Metabolomics Data Load In}

#Full datasets from Progenesis:
posugly <- read_csv(here('Data/Metabolomics/pos_metabolome_full.csv'))
negugly <- read_csv(here('Data/Metabolomics/neg_metabolome_full.csv'))
#Metadata
mdata_neg <- read_csv(here('Data/Metabolomics/metadata_neg.csv')) %>%
  mutate(group = ifelse(group == 'A', 'C_Type', 'E_type'))
mdata_pos <- read_csv(here('Data/Metabolomics/metadata_pos.csv')) %>%
  mutate(group = ifelse(group == 'A', 'C_Type', 'E_type'))

#Remove features which have a CV greater than 50:
pos_full <- posugly %>%
  filter(is.na(cv_g_50)) %>%
  dplyr::select(compound, starts_with('pos')) %>%
  mutate(compound = paste0(compound, '_pos')) %>%
  pivot_longer(starts_with('pos'), names_to = 'sample', values_to = 'intensity') %>%
  pivot_wider(names_from = 'compound', values_from = 'intensity')

neg_full <- negugly %>%
  filter(is.na(cv_g_50)) %>%
  dplyr::select(compound, starts_with('neg')) %>%
  mutate(compound = paste0(compound, '_neg')) %>%
  pivot_longer(starts_with('neg'), names_to = 'sample', values_to = 'intensity') %>%
  pivot_wider(names_from = 'compound', values_from = 'intensity')

#Scale our data:
pos_scaled <- pos_full %>% 
  column_to_rownames('sample') %>%
  log_transform() %>%
  pareto_scale()%>%
  as.data.frame() 

neg_scaled <- neg_full %>% 
  column_to_rownames('sample') %>%
  log_transform() %>%
  pareto_scale()%>%
  as.data.frame() 

#Generate the metadata to be in the same order as our metabolomics data
mpos <- left_join(data.frame(sample = rownames(pos_scaled)), mdata_pos)
mneg <- left_join(data.frame(sample = rownames(neg_scaled)), mdata_neg)

```

```{r Microbiome Alpha Diversity Analysis}

adiv <- ps_raw %>% 
  subset_samples(treatment != 'fecal_stock') %>%
  estimate_richness(measures = c('Observed','Shannon','Simpson')) %>%
  cbind(., data.frame(sample_data(ps_raw %>% 
                         subset_samples(treatment != 'fecal_stock'))))

gad <- adiv %>%
  pivot_longer(cols = c('Observed', 'Shannon', 'Simpson'), names_to = 'measure')

ggplot(gad, aes(x = treatment, y = value, color = fecal_sample)) +
  geom_point() +
  facet_wrap(vars(measure), scales = 'free', ncol = 3) +
  theme_cowplot() +
  theme(axis.text.x = element_text(angle = 90), axis.title.x = element_blank()) 

st <- gad %>%
  dplyr::select(fecal_sample, measure, value, treatment) %>%
  group_by(measure) %>%
  nest() %>%
  mutate(frt = map_dbl(data, function(x) friedman.test(value ~ treatment | fecal_sample, data = x)$p.value)) %>%
  mutate(padj =  p.adjust(frt, method = 'BH'))

```

```{r Microbiome Beta Diversity Analysis}

distmat <- phyloseq::distance(ps_final, method = 'bray')
#Extract the metadata
mdata <- data.frame(sample_data(ps_final)) %>% dplyr::select(fecal_sample, treatment, group) 
#Set the seed for reproducibility
set.seed(120)
#Run betadisper to verify the distrubtion of our groups is equal, an underlying assumption of PERMANOVA
bdisp <- betadisper(distmat, mdata$treatment)
#Evaluate using a permutation test
permutest(bdisp) 
adonis2(distmat~treatment, data = mdata) #p = 0.719: Not significant.

bdispGr <- betadisper(distmat, mdata$group)
#Evaluate using a permutation test
permutest(bdispGr) 
adonis2(distmat~group, data = mdata) #p = 0.001: Significant.

```

```{r Differential Abundance Analysis}

psglm <- ps_final_c %>%
  rarefy_even_depth() %>%
  psmelt()

glmnb <- psglm %>%
  group_by(OTU) %>%
  nest() %>%
  mutate_at( # change the data in 'lmer' column
    "data",
    purrr::map, # allows iteration over data in 'lmer' column, returns list
    function(x) {
      lmer <- try(glmer.nb(Abundance ~ treatment + (1 |fecal_sample), data = x), silent = TRUE) # do the lmer test
      c(lmer, x) # return results of lmer, as well as data for (r)anova later
    } 
  )

glmnbclean <- glmnb[sapply(glmnb$data, function(x) class(x[[1]]) !=  'character'),]

nvbroc <- list(treatment = c('no_veg', 'broc'))
nvbrus <- list(treatment = c('no_veg', 'brus'))
nvcombo <- list(treatment = c('no_veg', 'combo'))
brocbrus <- list(treatment = c('broc', 'brus'))
broccombo <- list(treatment = c('broc', 'combo'))
bruscombo <- list(treatment = c('brus', 'combo'))

l2fcmin <- function(x, counts, factor, class1, class2){
  x[[counts]] <- log2(x[[counts]]+sqrt(nzmin(x[[counts]])*0.001))
  c1 <- x[[counts]][sapply(x[[factor]], function(x) x == class1)]
  c2 <- x[[counts]][sapply(x[[factor]], function(x) x == class2)]
  lf2 <- mean(c1[sapply(c1,is.finite)]) - mean(c2[sapply(c2, is.finite)])
  return(lf2)
}

nzmin <- function(x){
  min(x[x > 0])
}

glmres <- glmnbclean %>%
  group_by(OTU) %>%
  group_modify(~{
    data.frame(test = c('NVvBroc', 'NVvBrus', 'NVvCombo', 'BrocvBrus', 'BrocvCombo', 'BrusvCombo'),
               pval = c(summary(testFactors(.x$data[[1]][[1]], levels = nvbroc))$anova.table[,3],
                        summary(testFactors(.x$data[[1]][[1]], levels = nvbrus))$anova.table[,3],
                        summary(testFactors(.x$data[[1]][[1]], levels = nvcombo))$anova.table[,3],
                        summary(testFactors(.x$data[[1]][[1]], levels = brocbrus))$anova.table[,3],
                        summary(testFactors(.x$data[[1]][[1]], levels = broccombo))$anova.table[,3],
                        summary(testFactors(.x$data[[1]][[1]], levels = bruscombo))$anova.table[,3]),
               l2fc = c(l2fcmin(x = .x$data[[1]], counts = 'Abundance', factor = 'treatment', class1 = 'no_veg', class2 = 'broc'),
               l2fc = l2fcmin(x = .x$data[[1]], counts = 'Abundance', factor = 'treatment', class1 = 'no_veg', class2 = 'brus'),
               l2fc = l2fcmin(x = .x$data[[1]], counts = 'Abundance', factor = 'treatment', class1 = 'no_veg', class2 = 'combo'),
               l2fc = l2fcmin(x = .x$data[[1]], counts = 'Abundance', factor = 'treatment', class1 = 'broc', class2 = 'brus'),
               l2fc = l2fcmin(x = .x$data[[1]], counts = 'Abundance', factor = 'treatment', class1 = 'broc', class2 = 'combo'),
               l2fc = l2fcmin(x = .x$data[[1]], counts = 'Abundance', factor = 'treatment', class1 = 'brus', class2 = 'combo')))
  }) %>%
  ungroup() %>%
  mutate(padj = p.adjust(pval, method = 'BH')) 

tx <- data.frame(tax_table(ps_final_c)) %>%
  rownames_to_column('OTU')

glmrsig <- glmres %>%
  filter(padj <= 0.05)

```

```{r Metabolomics Repeated Measures ANOVA}
#Repeated measures ANOVA conducted in Progenesis - Evaluating output in R
#Load in the progenesis output
pos_prog <- read_csv(here('Data/Metabolomics/pos_metabolome_full.csv'))
neg_prog <- read_csv(here('Data/Metabolomics/neg_metabolome_full.csv'))

#Filter the progenesis output down to only the features of interest that came out as significant
prog_sig_pos <- pos_prog %>%
  filter(!is.na(q_u_05)) %>%
  dplyr::select(compound, starts_with('pos')) %>%
  mutate(compound = paste0(compound, '_pos')) %>%
  pivot_longer(starts_with('pos'), names_to = 'sample', values_to = 'intensity') %>%
  pivot_wider(names_from = 'compound', values_from = 'intensity')

prog_sig_neg <- neg_prog %>%
  filter(!is.na(q_u_05)) %>%
  dplyr::select(compound, starts_with('neg')) %>%
  mutate(compound = paste0(compound, '_neg')) %>%
  pivot_longer(starts_with('neg'), names_to = 'sample', values_to = 'intensity') %>%
  pivot_wider(names_from = 'compound', values_from = 'intensity')

rmanova_sig_neg <- colnames(prog_sig_neg)[-1]
rmanova_sig_pos <- colnames(prog_sig_pos)[-1]

```

```{r Metabolomics Metabotype GLMM}
#Wrangle and clean the data
lmer_data_pos <- mdata_pos %>%
  select(sample, treatment, fecal_sample, group) %>%
  right_join(pos_scaled %>% rownames_to_column('sample')) %>% 
  filter(treatment != 'no_veg') %>% #Remove from analysis as it has different variance from the rest of the samples
  column_to_rownames('sample') %>%
  select(where(is.numeric)) %>%
  select(which(apply(., 2, sd) != 0)) %>% #Remove samples with 0 variance
  rownames_to_column('sample') %>%
  left_join(mdata_pos %>% select(sample, treatment, fecal_sample, group)) %>%
  pivot_longer(cols = where(is.numeric), names_to = 'feature', values_to = 'intensity')

#Run the model on just the vegetable data
lmer_pos <- lmer_data_pos %>% 
  group_by(feature) %>%
  nest() %>% # makes tibble of data for each feature, saves as 'lmer' column
  mutate_at( # change the data in 'lmer' column
    "data",
    purrr::map, # allows iteration over data in 'lmer' column, returns list
    function(x) {
      lmer <- lmerTest::lmer(intensity ~ treatment + group + treatment * group + (1 |fecal_sample), data = x) # do the lmer test
      c(lmer, x) # return results of lmer, as well as data for (r)anova later
    } 
  )

#Run contrasts
broc_pos <- lmer_pos %>%
  group_by(feature) %>%
  group_modify(~ {
    contest(.x$data[[1]][[1]], c(0,0,0,1,0,0), joint = FALSE)
  }) %>%
  set_colnames(c('feature', 'estimate', 'stderror', 'df', 'tvalue', 'lower', 'upper', 'pvalue')) %>%
  inset('term', value = 'broc') %>%
  ungroup()

brus_pos <- lmer_pos %>%
  group_by(feature) %>%
  group_modify(~ {
    contest(.x$data[[1]][[1]], c(0,0,0,1,1,0), joint = FALSE)
  }) %>%
  set_colnames(c('feature', 'estimate', 'stderror', 'df', 'tvalue', 'lower', 'upper', 'pvalue')) %>%
  inset('term', value = 'brus') %>%
  ungroup()

combo_pos <- lmer_pos %>%
  group_by(feature) %>%
  group_modify(~ {
    contest(.x$data[[1]][[1]], c(0,0,0,1,0,1), joint = FALSE)
  }) %>%
  set_colnames(c('feature', 'estimate', 'stderror', 'df', 'tvalue', 'lower', 'upper', 'pvalue')) %>%
  inset('term', value = 'combo') %>%
  ungroup()

#Wrangle data for the control model
control_data_pos <- mdata_pos %>%
  select(sample, treatment, fecal_sample, group) %>%
  right_join(pos_scaled %>% rownames_to_column('sample')) %>% 
  filter(treatment != 'no_veg') %>% #Remove from analysis as it has different variance from the rest of the samples
  column_to_rownames('sample') %>%
  select(where(is.numeric)) %>%
  select(which(apply(., 2, sd) != 0)) %>% #Remove samples with 0 variance
  rownames_to_column('sample') %>%
  left_join(mdata_pos %>% select(sample, treatment, fecal_sample, group)) %>%
  pivot_longer(cols = where(is.numeric), names_to = 'feature', values_to = 'intensity')

#Run the control model
control_model_pos <- control_data_pos %>% 
  group_by(feature) %>%
  nest() %>% # makes tibble of data for each feature, saves as 'lmer' column
  mutate_at( # change the data in 'lmer' column
    "data",
    purrr::map, # allows iteration over data in 'lmer' column, returns list
    function(x) {
      lmr <- lm(intensity ~ group, data = x) %>% # do the lmer test
        summary() %>%
        broom::tidy()
      lmr[2,] # return results of lmer, as well as data for (r)anova later
    } 
  ) %>%
  unnest('data') %>%
  rename('pval' = p.value) %>%
  mutate(padj = p.adjust(pval, method = 'BH')) %>%
  select(feature, pval, padj)

sig_control_pos <- control_model_pos %>%
  filter(padj <= 0.05) %>%
  pull(feature)

#Wrangle data
lmer_data_neg <- mdata_neg %>%
  select(sample, treatment, fecal_sample, group) %>%
  right_join(neg_scaled %>% rownames_to_column('sample')) %>% 
  filter(treatment != 'no_veg') %>% #Remove from analysis as it has different variance from the rest of the samples
  column_to_rownames('sample') %>%
  select(where(is.numeric)) %>%
  select(which(apply(., 2, sd) != 0)) %>% #Remove samples with 0 variance
  rownames_to_column('sample') %>%
  left_join(mdata_neg %>% select(sample, treatment, fecal_sample, group)) %>%
  pivot_longer(cols = where(is.numeric), names_to = 'feature', values_to = 'intensity')

#Run the model
lmer_neg <- lmer_data_neg %>% 
  group_by(feature) %>%
  nest() %>% # makes tibble of data for each feature, saves as 'lmer' column
  mutate_at( # change the data in 'lmer' column
    "data",
    purrr::map, # allows iteration over data in 'lmer' column, returns list
    function(x) {
      lmer <- lmerTest::lmer(intensity ~ treatment + group + treatment * group + (1 |fecal_sample), data = x) # do the lmer test
      c(lmer, x) # return results of lmer, as well as data for (r)anova later
    } 
  )

#Run contrasts
broc_neg <- lmer_neg %>%
  group_by(feature) %>%
  group_modify(~ {
    contest(.x$data[[1]][[1]], c(0,0,0,1,0,0), joint = FALSE)
  }) %>%
  set_colnames(c('feature', 'estimate', 'stderror', 'df', 'tvalue', 'lower', 'upper', 'pvalue')) %>%
  inset('term', value = 'broc') %>%
  ungroup()

brus_neg <- lmer_neg %>%
  group_by(feature) %>%
  group_modify(~ {
    contest(.x$data[[1]][[1]], c(0,0,0,1,1,0), joint = FALSE)
  }) %>%
  set_colnames(c('feature', 'estimate', 'stderror', 'df', 'tvalue', 'lower', 'upper', 'pvalue')) %>%
  inset('term', value = 'brus') %>%
  ungroup()

combo_neg <- lmer_neg %>%
  group_by(feature) %>%
  group_modify(~ {
    contest(.x$data[[1]][[1]], c(0,0,0,1,0,1), joint = FALSE)
  }) %>%
  set_colnames(c('feature', 'estimate', 'stderror', 'df', 'tvalue', 'lower', 'upper', 'pvalue')) %>%
  inset('term', value = 'combo') %>%
  ungroup()

#Wrangle control model
control_data_neg <- mdata_neg %>%
  select(sample, treatment, fecal_sample, group) %>%
  right_join(neg_scaled %>% rownames_to_column('sample')) %>% 
  filter(treatment != 'no_veg') %>% #Remove from analysis as it has different variance from the rest of the samples
  column_to_rownames('sample') %>%
  select(where(is.numeric)) %>%
  select(which(apply(., 2, sd) != 0)) %>% #Remove samples with 0 variance
  rownames_to_column('sample') %>%
  left_join(mdata_neg %>% select(sample, treatment, fecal_sample, group)) %>%
  pivot_longer(cols = where(is.numeric), names_to = 'feature', values_to = 'intensity')

#Run control model
control_model_neg <- control_data_neg %>% 
  group_by(feature) %>%
  nest() %>% # makes tibble of data for each feature, saves as 'lmer' column
  mutate_at( # change the data in 'lmer' column
    "data",
    purrr::map, # allows iteration over data in 'lmer' column, returns list
    function(x) {
      lmr <- lm(intensity ~ group, data = x) %>% # do the lmer test
        summary() %>%
        broom::tidy()
      lmr[2,] # return results of lmer, as well as data for (r)anova later
    } 
  ) %>%
  unnest('data') %>%
  rename('pval' = p.value) %>%
  mutate(padj = p.adjust(pval, method = 'BH')) %>%
  select(feature, pval, padj)

#Extract features we care about
sig_control_neg <- control_model_neg %>%
  filter(padj <= 0.05) %>%
  pull(feature)

unique_neg <- rbind(broc_neg, brus_neg, combo_neg) %>%
  mutate(padj = p.adjust(pvalue, method = 'BH')) %>%
  dplyr::filter(padj <= 0.05) %>%
  filter(!feature %in% sig_control_neg)

unique_pos <- rbind(broc_pos, brus_pos, combo_pos) %>%
  mutate(padj = p.adjust(pvalue, method = 'BH')) %>%
  dplyr::filter(padj <= 0.05) %>%
  filter(!feature %in% sig_control_pos)

final_neg <- rbind(broc_neg, brus_neg, combo_neg) %>%
  mutate(padj = p.adjust(pvalue, method = 'BH')) %>%
  dplyr::filter(padj <= 0.05) 

final_pos <- rbind(broc_pos, brus_pos, combo_pos) %>%
  mutate(padj = p.adjust(pvalue, method = 'BH')) %>%
  dplyr::filter(padj <= 0.05) 

glmm_sig_neg <- unique(final_neg$feature)
glmm_sig_pos <- unique(final_pos$feature)

```

```{r Data Prep for Multi-Omic Integration}

#Data was rung thru MSCombine and then reuploaded here:
#Load in the data from MSCombine
mscp_raw <- read_csv(here('Data/Metabolomics/mscPos.csv'))
mscn_raw <- read_csv(here('Data/Metabolomics/mscNeg.csv'))

mscp <- mscp_raw %>%
  dplyr::select(-neutral_mass, -mz, -charge, -rt) %>%
  mutate(compound = paste0(compound, '_pos')) %>%
  column_to_rownames('compound') %>%
  t() %>%
  as.data.frame() %>%
  log_transform() %>%
  pareto_scale()

mscn <- mscn_raw %>%
  dplyr::select(-neutral_mass, -mz, -charge, -rt) %>%
  mutate(compound = paste0(compound, '_neg')) %>%
  column_to_rownames('compound') %>%
  t() %>%
  as.data.frame() %>%
  log_transform() %>%
  pareto_scale()

combined_set <- as.data.frame(cbind(mscn, mscp))
rownames(combined_set) <- gsub('neg', 'ms', rownames(combined_set))

#New metatdata for the combined sets
mcom <- mneg %>%
  mutate(sample = gsub('neg', 'ms', sample)) 

multiset_wide <-  combined_set %>%
  rename_with(~paste0('FT_', .x)) %>%
  rownames_to_column('sample') %>%
  left_join(microdata)

multiset_tidy <- multiset_wide %>%
  pivot_longer(cols = starts_with('FT'), values_to = 'intensity', names_to = 'feature') %>%
  pivot_longer(cols = starts_with('ASV'), values_to = 'relab', names_to = 'ASV') %>%
  left_join(mcom)

rownames(microdata_c) <- NULL
micro_clr <- microdata_c %>%
  column_to_rownames('sample') %>%
  clr() %>%
  rownames_to_column('sample')

multiset_wide_clr <-  combined_set %>%
  rename_with(~paste0('FT_', .x)) %>%
  rownames_to_column('sample') %>%
  left_join(micro_clr)

multiset_tidy_clr <- multiset_wide_clr %>%
  pivot_longer(cols = starts_with('FT'), values_to = 'intensity', names_to = 'feature') %>%
  pivot_longer(cols = starts_with('ASV'), values_to = 'relab', names_to = 'ASV') %>%
  left_join(mcom)

ft_block <- multiset_wide_clr %>%
  dplyr::select(starts_with('FT'))

asv_block <- multiset_wide %>%
  dplyr::select(starts_with('ASV'))

asv_block_clr <- multiset_wide_clr %>%
  dplyr::select(starts_with('ASV'))

#Recreate the metadata to make sure that they are in the same order as the features
multiset_meta <- multiset_wide %>%
  dplyr::select('sample') %>%
  left_join(mcom) 

```

```{r Multiblock PLS-DA}
Xdiablo <- list(micro = asv_block_clr,
          metab = ft_block)
trt <- as.factor(multiset_meta$treatment)

#Adjust our data to handle repeated measures
Cov <- data.frame(subject_id = as.factor(multiset_meta$fecal_sample))
A <- lapply(Xdiablo, function(i) withinVariation(X = i, design = Cov))

#Create the design matrix:
design <- matrix(1, nrow = 3, ncol = 3)
diag(design) <- 0

keepX <- list(micro = c(15,15), metab = c(100, 100))
diablo <- block.splsda(X = A, Y = trt, keepX = keepX, ncomp = 8, design = design)

#Create the consensus space by finding the average loadings of each compononet
conDiablo <- data.frame(Reduce('+', diablo$variates)/2) %>%
  cbind(trt)


dtestloo <- perf(diablo, validation = 'loo', auc = TRUE, progressBar = FALSE)

#Extract out the data to make the ROC curves
metab1 <- as.data.frame(dtestloo$predict$nrep1$metab$comp1)
metab2 <- as.data.frame(dtestloo$predict$nrep1$metab$comp2)
micro1 <- as.data.frame(dtestloo$predict$nrep1$micro$comp1)
micro2 <- as.data.frame(dtestloo$predict$nrep1$micro$comp2)

#Make the class matrix
classmat <- data.frame(class = diablo$Y) %>%
  mutate(broc = ifelse(class == 'broc', 1, 0)) %>%
  mutate(brus = ifelse(class == 'brus', 1, 0)) %>%
  mutate(combo = ifelse(class == 'combo', 1, 0)) %>%
  mutate(no_veg = ifelse(class == 'no_veg', 1, 0)) %>%
  dplyr::select(-class)

#Build a list of the outputs 
outputs <- list(metab_comp1 = metab1, metab_comp2 = metab2, micro_comp1 = micro1, micro_comp2 = micro2)

#Custom function to pull the classes and see how they do
pull_roc <- function(prediction_list, classes){
  purrr::map(prediction_list, function(x){
    map2(classes, x, roc)
  })
}

#Pull out the ROCS
rocs <- pull_roc(outputs, classmat)
#Make them into nice plots using ggroc
rocplots <- purrr::map(rocs, ggroc)
#Extract out the AUCs 
aucs <- purrr::map(rocs, function(x) purrr::map(x, auc))
pal <- RColorBrewer::brewer.pal(4, 'Dark2')
names(pal) <- c('broc', 'brus', 'combo', 'NC')
palmb <- pal
names(palmb) <- c('broc', 'brus', 'combo', 'no_veg')

#Make the plots pretty
p1 <- rocplots[[1]] +
  geom_path(size = 2) + 
  geom_abline(intercept = 1) +
  cowplot::theme_cowplot() +
  scale_color_manual(values = palmb,
                     name = 'Outcome',
                     labels = c(paste0('Broc vs All: ', round(aucs[[1]][[1]], 3)),
                                paste0('Brus vs All: ', round(aucs[[1]][[2]], 3)),
                                paste0('Combo vs All: ', round(aucs[[1]][[3]], 3)),
                                paste0('NC vs All: ', round(aucs[[1]][[4]], 3)))) +
  ggtitle('Metabolome - Component 1')  +
  theme(legend.position = c(0.5,0.25))

p2 <- rocplots[[2]] +
  geom_path(size = 2) + 
  geom_abline(intercept = 1) +
  cowplot::theme_cowplot() +
  scale_color_manual(values = palmb,
                     name = 'Outcome',
                     labels = c(paste0('Broc vs All: ', round(aucs[[2]][[1]], 3)),
                                paste0('Brus vs All: ', round(aucs[[2]][[2]], 3)),
                                paste0('Combo vs All: ', round(aucs[[2]][[3]], 3)),
                                paste0('NC vs All: ', round(aucs[[2]][[4]], 3)))) +
  ggtitle('Metabolome - Component 2')  +
  theme(legend.position = c(0.5,0.25))

p3 <- rocplots[[3]] +
  geom_path(size = 2) + 
  geom_abline(intercept = 1) +
  cowplot::theme_cowplot() +
  scale_color_manual(values = palmb,
                     name = 'Outcome',
                     labels = c(paste0('Broc vs All: ', round(aucs[[3]][[1]], 3)),
                                paste0('Brus vs All: ', round(aucs[[3]][[2]], 3)),
                                paste0('Combo vs All: ', round(aucs[[3]][[3]], 3)),
                                paste0('NC vs All: ', round(aucs[[3]][[4]], 3)))) +
  ggtitle('Microbiome - Component 1')  +
  theme(legend.position = c(0.5,0.25))

p4 <- rocplots[[4]] +
  geom_path(size = 2) + 
  geom_abline(intercept = 1) +
  cowplot::theme_cowplot() +
  scale_color_manual(values = palmb,
                     name = 'Outcome',
                     labels = c(paste0('Broc vs All: ', round(aucs[[4]][[1]], 3)),
                                paste0('Brus vs All: ', round(aucs[[4]][[2]], 3)),
                                paste0('Combo vs All: ', round(aucs[[4]][[3]], 3)),
                                paste0('NC vs All: ', round(aucs[[4]][[4]], 3)))) +
  ggtitle('Microbiome - Component 2')  +
  theme(legend.position = c(0.5,0.25))

#Put them all together
allroc <- plot_grid(p1, p2, p3, p4, ncol = 2)

allroc
```

```{r Microbial Filter Approach}
#Function to read in Progenesis output
readprog <- function(x){
  #Read in the data
  data <- read_csv(x, skip = 2)
  #Pull the metadata
  metadata <- as.character(read_csv(x)[1,])
  #Pull other info including if it raw Abundance
  abinfo <- colnames(read_csv(x))
  #Filter 
  dclean <- data[,1:(which(abinfo == 'Raw abundance')-1)]
  mclean <- metadata[1:(which(abinfo == 'Raw abundance')-1)]
  inc <- c(which(mclean != 'NA'), (length(mclean)+1))
  nm <- diff(inc)
  mc <- c()
  for(i in 1:length(nm)){
    cf <- rep(mclean[inc[i]], nm[i])
    mc <- c(mc, cf)
  }
  sn <- sapply(str_split(colnames(dclean)[16:length(dclean)], '\\.\\.\\.'), function(x) x[1])
  sampleinfo <- data.frame(sample = sn,
                           class = mc)
  colnames(dclean)[16:ncol(dclean)] <- sn
  final <- dclean %>%
    pivot_longer(cols = 16:(ncol(dclean)-1), names_to = 'sample', values_to = 'intensity') %>%
    left_join(sampleinfo)
  return(final)
}

progdata_pos <- readprog(here('Data/Metabolomics/ProgenesisOutputPos.csv'))
progdata_neg <- readprog(here('Data/Metabolomics/ProgenesisOutputNeg.csv'))

data_pos <- progdata_pos %>%
  dplyr::select(Compound, sample, intensity, class) %>%
  group_by(Compound, class) %>%
  summarise(meanint = mean(intensity)) %>%
  pivot_wider(names_from = 'class', values_from = 'meanint')

#Initial screening to find the metabolites of interest
icpos <- data_pos %>%
  filter(`Fecal + Broc` > 2*`Fecal`) %>%
  filter(`Fecal + Brus` > 2*`Fecal`) %>%
  filter(`Fecal + Combo` > 2*`Fecal`) %>%
  filter(Blank < 0.05) %>%
  filter(`Media alone` < 5) %>%
  filter(Fecal < 18) %>%
  filter(`Veg media` < 14) #117

data_neg <- progdata_neg %>%
  dplyr::select(Compound, sample, intensity, class) %>%
  group_by(Compound, class) %>%
  summarise(meanint = mean(intensity)) %>%
  pivot_wider(names_from = 'class', values_from = 'meanint')

icneg <- data_neg %>%
  filter(`Fecal + Broc` > 2*`Fecal`) %>%
  filter(`Fecal + Brus` > 2*`Fecal`) %>%
  filter(`Fecal + Combo` > 2*`Fecal`) %>%
  filter(Blank < 0.05) %>%
  filter(`Media alone` < 5) %>%
  filter(Fecal < 18) %>%
  filter(`Veg in media` < 14) #270

#Load in the metadata
mdata_neg <- read_csv(here('Data/Metabolomics/metadata_neg.csv')) %>%
  mutate(group = ifelse(group == 'A', 'C_Type', 'E_type'))
mdata_pos <- read_csv(here('Data/Metabolomics/metadata_pos.csv')) %>%
  mutate(group = ifelse(group == 'A', 'C_Type', 'E_type'))

#Pull from the raw data
mpos <- progdata_pos %>%
  #Format data appropriately
  dplyr::select(Compound, sample, intensity, class) %>%
  mutate(class = ifelse(class == 'Fecal', 'NC', 
                        ifelse(class == 'Fecal + Broc', 'Broc',
                               ifelse(class == 'Fecal + Brus', 'Brus',
                                      ifelse(class == 'Fecal + Combo', 'Combo', 'Other'))))) %>%
  filter(class != 'Other') %>%
  #Filter to only the compounds we care about
  filter(Compound %in% icpos$Compound) %>%
  modify_at('class', factor, levels = c('NC', 'Broc', 'Brus', 'Combo')) %>%
  left_join(mdata_pos) %>%
  modify_at('fecal_sample', factor) %>%
  group_by(Compound) %>%
  nest() %>%
  #Use a Friedman test (non-parametric RMANOVA) to evaluate is there is a group difference
  mutate(p_val = map_dbl(data, function(x) friedman.test(intensity ~ class | fecal_sample, x)$p.value)) %>%
  ungroup() %>%
  #Filter to only significant results
  mutate(padj = p.adjust(p_val, method = 'BH')) %>%
  filter(padj <= 0.05) %>% #113/117 
  mutate(ntest = purrr::map(data, function(x) PMCMRplus::frdAllPairsNemenyiTest(intensity ~ class | fecal_sample, x))) %>%
  mutate(NCvBroc = map_dbl(ntest, function(x) x$p.value[1,1])) %>%
  mutate(NCvBroc_adj = p.adjust(NCvBroc, method = 'BH')) %>%
  mutate(NCvBrus = map_dbl(ntest, function(x) x$p.value[2,1])) %>%
  mutate(NCvBrus_adj = p.adjust(NCvBrus, method = 'BH')) %>%
  mutate(NCvCombo = map_dbl(ntest, function(x) x$p.value[3,1])) %>%
  mutate(NCvCombo_adj = p.adjust(NCvCombo, method = 'BH')) %>%
  mutate(BrocvBrus = map_dbl(ntest, function(x) x$p.value[2,2])) %>%
  mutate(BrocvBrus_adj = p.adjust(BrocvBrus, method = 'BH')) %>%
  mutate(BrocvCombo = map_dbl(ntest, function(x) x$p.value[3,2])) %>%
  mutate(BrocvCombo_adj = p.adjust(BrocvCombo, method = 'BH')) %>%
  mutate(BrusvCombo = map_dbl(ntest, function(x) x$p.value[3,3])) %>%
  mutate(BrusvCombo_adj = p.adjust(BrusvCombo, method = 'BH')) %>%
  dplyr::select(-data, -ntest)


mneg <- progdata_neg %>%
  dplyr::select(Compound, sample, intensity, class) %>%
  mutate(class = ifelse(class == 'Fecal', 'NC', 
                        ifelse(class == 'Fecal + Broc', 'Broc',
                               ifelse(class == 'Fecal + Brus', 'Brus',
                                      ifelse(class == 'Fecal + Combo', 'Combo', 'Other'))))) %>%
  filter(class != 'Other') %>%
  filter(Compound %in% icneg$Compound) %>%
  modify_at('class', factor, levels = c('NC', 'Broc', 'Brus', 'Combo')) %>%
  left_join(mdata_neg) %>%
  modify_at('fecal_sample', factor) %>%
  group_by(Compound) %>%
  nest() %>%
  mutate(p_val = map_dbl(data, function(x) friedman.test(intensity ~ class | fecal_sample, x)$p.value)) %>%
  ungroup() %>%
  mutate(padj = p.adjust(p_val, method = 'BH')) %>%
  filter(padj <= 0.05) %>% #260/270 
  mutate(ntest = purrr::map(data, function(x) PMCMRplus::frdAllPairsNemenyiTest(intensity ~ class | fecal_sample, x))) %>%
  mutate(NCvBroc = map_dbl(ntest, function(x) x$p.value[1,1])) %>%
  mutate(NCvBroc_adj = p.adjust(NCvBroc, method = 'BH')) %>%
  mutate(NCvBrus = map_dbl(ntest, function(x) x$p.value[2,1])) %>%
  mutate(NCvBrus_adj = p.adjust(NCvBrus, method = 'BH')) %>%
  mutate(NCvCombo = map_dbl(ntest, function(x) x$p.value[3,1])) %>%
  mutate(NCvCombo_adj = p.adjust(NCvCombo, method = 'BH')) %>%
  mutate(BrocvBrus = map_dbl(ntest, function(x) x$p.value[2,2])) %>%
  mutate(BrocvBrus_adj = p.adjust(BrocvBrus, method = 'BH')) %>%
  mutate(BrocvCombo = map_dbl(ntest, function(x) x$p.value[3,2])) %>%
  mutate(BrocvCombo_adj = p.adjust(BrocvCombo, method = 'BH')) %>%
  mutate(BrusvCombo = map_dbl(ntest, function(x) x$p.value[3,3])) %>%
  mutate(BrusvCombo_adj = p.adjust(BrusvCombo, method = 'BH')) %>%
  dplyr::select(-data, -ntest)

canopus_pos <- read_csv(here('Data/Metabolomics/PosCanopusFinal.csv'))
canopus_neg <- read_csv(here('Data/Metabolomics/NegCanopusFinal.csv'))

suptab_pos <- mpos %>%
  left_join(canopus_pos, by = c('Compound' = 'progenesis_id')) %>%
  magrittr::inset('Polarity', value = 'Positive')

suptab_neg <- mneg %>%
  left_join(canopus_neg, by = c('Compound' = 'progenesis_id')) %>%
  magrittr::inset('Polarity', value = 'Negative')

suptab_final <- rbind(suptab_pos, suptab_neg)

#Filter to only the compounds of interest
class_pos <- canopus_pos %>%
  filter(progenesis_id %in% mpos$Compound) 

class_neg <- canopus_neg %>%
  filter(progenesis_id %in% mneg$Compound) 

#Calculate the number of each class there is in the data
nc <- class_neg %>%
  group_by(`most specific class`) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  #Filter out peptides and amino acids because they're boring an annoying
#  filter(!str_detect(`most specific class`, '[Pp]eptide')) %>%
#  filter(!str_detect(`most specific class`, '[Aa]mino acid')) %>%
  mutate(class_n = paste0(`most specific class`, ' (', n, ')')) 
  
pc <- class_pos %>%
  group_by(`most specific class`) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  #filter(!str_detect(`most specific class`, '[Pp]eptide')) %>%
  #filter(!str_detect(`most specific class`, '[Aa]mino acid')) %>%
  mutate(class_n = paste0(`most specific class`, ' (', n, ')')) 

#Combined
mc <- rbind(class_pos, class_neg) %>%
  group_by(`most specific class`) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  #filter(!str_detect(`most specific class`, '[Pp]eptide')) %>%
  #filter(!str_detect(`most specific class`, '[Aa]mino acid')) %>%
  mutate(class_n = paste0(`most specific class`, ' (', n, ')')) 

#Format the ASV data for correlation analysis
micro_asv <- ps_final_c %>%
  #Subest to only the samples we ant
  subset_samples(treatment != 'no_veg') %>%
  #Agglomerate the taxa the Genus level
  tax_glom('Genus') %>%
  #Pull the OTU table
  otu_table() %>%
  as.data.frame() %>%
  #Complete clr transformation
  clr() %>%
  #Convert sample data to a column
  rownames_to_column('sample') %>%
  modify_at('sample', as.integer) %>%
  #Combine the metadata in to have the metabolomics sample
  left_join(., as.data.frame(sample_data(ps_final))) %>%
  dplyr::select(metabolomics_pos_sample, starts_with('ASV')) %>%
  #Fix names to be generic MS names as opposed to a polarity
  mutate(sample = gsub('pos', 'ms', metabolomics_pos_sample)) %>%
  dplyr::select(sample, starts_with('ASV'))


#Pull out the raw metabolomics data
raw_pos_data <- progdata_pos %>%
  #Format data appropriately
  dplyr::select(Compound, sample, intensity, class) %>%
  mutate(class = ifelse(class == 'Fecal', 'NC', 
                        ifelse(class == 'Fecal + Broc', 'Broc',
                               ifelse(class == 'Fecal + Brus', 'Brus',
                                      ifelse(class == 'Fecal + Combo', 'Combo', 'Other'))))) %>%
  #Filter to only the compounds we care about
  filter(!class %in% c('Other', 'NC')) %>%
  filter(Compound %in% mpos$Compound) %>%
  modify_at('class', factor, levels = c('NC', 'Broc', 'Brus', 'Combo')) %>%
  left_join(mdata_pos) %>%
  modify_at('fecal_sample', factor) #%>%
  #Make it so that we know which polarity the information is coming from
  #mutate(feature = paste0(Compound, '_pos'))

raw_neg_data <- progdata_neg %>%
  #Format data appropriately
  dplyr::select(Compound, sample, intensity, class) %>%
  mutate(class = ifelse(class == 'Fecal', 'NC', 
                        ifelse(class == 'Fecal + Broc', 'Broc',
                               ifelse(class == 'Fecal + Brus', 'Brus',
                                      ifelse(class == 'Fecal + Combo', 'Combo', 'Other'))))) %>%
  filter(!class %in% c('Other', 'NC')) %>%
  #Filter to only the compounds we care about
  filter(Compound %in% mneg$Compound) %>%
  modify_at('class', factor, levels = c('NC', 'Broc', 'Brus', 'Combo')) %>%
  left_join(mdata_neg) %>%
  modify_at('fecal_sample', factor) #%>%
  #Make it so that we know which polarity the information is coming from
  #mutate(feature = paste0(Compound, '_neg'))
  
full_raw <- rbind(raw_neg_data, raw_pos_data) %>%
  #mutate(feature = paste0(gsub('m/z', '', Compound), '_', gsub('_[[:digit:]]{1,2}', '', sample))) %>%
  mutate(sample = gsub('pos', 'ms', sample)) %>%
  mutate(sample = gsub('neg', 'ms', sample))

#Pull out releavant metadata
raw_meta <- full_raw %>%
  dplyr::select(sample, class) %>%
  distinct() 

metab_clean <- full_raw %>%
  #Select relevant columns
  dplyr::select(sample, Compound, intensity) %>%
  #Pivot wider for transformation
  pivot_wider(names_from = 'Compound', values_from = intensity) %>%
  column_to_rownames('sample') %>%
  #Scale and transfrom the data
  pareto_scale() %>%
  log_transform() %>%
  as.data.frame() %>%
  rownames_to_column('sample') %>%
  #Turn back tidy
  pivot_longer(where(is.numeric), names_to = 'feature', values_to = 'intensity') 

combined_data <- metab_clean %>%
  #Join on the microbiome data
  left_join(micro_asv) %>%
  #Make tidy
  pivot_longer(starts_with('ASV'), names_to = 'ASV', values_to = 'relab') 

cor_analysis <- combined_data %>%
  #Group and nest
  group_by(feature, ASV) %>%
  nest() %>%
  #Run the correlation analysis
  mutate(rho = map_dbl(data, function(x) cor(x$intensity, x$relab, method = 'spearman'))) %>%
  #Drop the data column because we don't need it
  dplyr::select(-data) %>%
  #Make wide
  pivot_wider(names_from = 'ASV', values_from = 'rho') %>%
  ungroup()

```



